services:
  scene_splitter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: scene_splitter_service
    ports:
      - "7001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-net

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: scene_splitter_worker
    command: celery -A app.utils.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app-net

networks:
  app-net:
    external: true
