version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./advanced.config:/etc/rabbitmq/advanced.config:ro
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    name: app-net
    external: false
