"""

Revision ID: 17c92d0c0aa5
Revises: 
Create Date: 2025-11-02 17:32:27.570050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17c92d0c0aa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_generator_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('configuration', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_image_generator_configurations_id'), 'image_generator_configurations', ['id'], unique=False)
    op.create_table('inbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_events_event_type'), 'inbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_inbox_events_idempotency_key'), 'inbox_events', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_inbox_events_processed'), 'inbox_events', ['processed'], unique=False)
    op.create_table('scene_representations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_uuid', sa.String(length=100), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_uuid', 'scene_number', name='uq_story_scene')
    )
    op.create_index(op.f('ix_scene_representations_id'), 'scene_representations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scene_representations_id'), table_name='scene_representations')
    op.drop_table('scene_representations')
    op.drop_index(op.f('ix_inbox_events_processed'), table_name='inbox_events')
    op.drop_index(op.f('ix_inbox_events_idempotency_key'), table_name='inbox_events')
    op.drop_index(op.f('ix_inbox_events_event_type'), table_name='inbox_events')
    op.drop_table('inbox_events')
    op.drop_index(op.f('ix_image_generator_configurations_id'), table_name='image_generator_configurations')
    op.drop_table('image_generator_configurations')
    # ### end Alembic commands ###
