"""

Revision ID: 2c980d1b2c1b
Revises: bef5d7ace1ad
Create Date: 2025-11-03 22:51:25.213807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c980d1b2c1b'
down_revision = 'bef5d7ace1ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_events', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_inbox_events_locked_until'), 'inbox_events', ['locked_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inbox_events_locked_until'), table_name='inbox_events')
    op.drop_column('inbox_events', 'locked_until')
    # ### end Alembic commands ###
