"""

Revision ID: 2e095532aaa0
Revises: 2c980d1b2c1b
Create Date: 2025-11-05 13:57:41.182221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e095532aaa0'
down_revision = '2c980d1b2c1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_events', sa.Column('story_uuid', sa.String(length=100), nullable=True))
    op.add_column('inbox_events', sa.Column('scene_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inbox_events_scene_number'), 'inbox_events', ['scene_number'], unique=False)
    op.create_index(op.f('ix_inbox_events_story_uuid'), 'inbox_events', ['story_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inbox_events_story_uuid'), table_name='inbox_events')
    op.drop_index(op.f('ix_inbox_events_scene_number'), table_name='inbox_events')
    op.drop_column('inbox_events', 'scene_number')
    op.drop_column('inbox_events', 'story_uuid')
    # ### end Alembic commands ###
