"""

Revision ID: bef5d7ace1ad
Revises: e5c97e3aa26a
Create Date: 2025-11-03 21:58:59.068293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef5d7ace1ad'
down_revision = 'e5c97e3aa26a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('story_uuid', sa.String(length=100), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('minio_path', sa.String(length=500), nullable=False),
    sa.Column('minio_bucket', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.String(length=100), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_images_id'), 'generated_images', ['id'], unique=False)
    op.create_index(op.f('ix_generated_images_scene_number'), 'generated_images', ['scene_number'], unique=False)
    op.create_index(op.f('ix_generated_images_story_uuid'), 'generated_images', ['story_uuid'], unique=False)
    op.create_index('ix_story_scene', 'generated_images', ['story_uuid', 'scene_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_story_scene', table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_story_uuid'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_scene_number'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_id'), table_name='generated_images')
    op.drop_table('generated_images')
    # ### end Alembic commands ###
