"""add key to image_generator_configurations and init default config

Revision ID: e5c97e3aa26a
Revises: 17c92d0c0aa5
Create Date: 2025-11-03 20:43:07.611555

"""
from alembic import op
import sqlalchemy as sa
import json
from uuid import uuid4


# revision identifiers, used by Alembic.
revision = 'e5c97e3aa26a'
down_revision = '17c92d0c0aa5'
branch_labels = None
depends_on = None


DEFAULT_WORKFLOW_TEMPLATE = {
    "1": {
        "inputs": {"ckpt_name": "{{model_name}}"},
        "class_type": "CheckpointLoaderSimple",
        "_meta": {"title": "Load Checkpoint"}
    },
    "2": {
        "inputs": {"text": "{{prompt}}", "clip": ["1", 1]},
        "class_type": "CLIPTextEncode",
        "_meta": {"title": "CLIP Text Encode (Prompt)"}
    },
    "3": {
        "inputs": {"text": "", "clip": ["1", 1]},
        "class_type": "CLIPTextEncode",
        "_meta": {"title": "CLIP Text Encode (Prompt)"}
    },
    "4": {
        "inputs": {
            "seed": "{{seed}}",
            "steps": "{{steps}}",
            "cfg": "{{cfg}}",
            "sampler_name": "{{sampler_name}}",
            "scheduler": "{{scheduler}}",
            "denoise": 1,
            "model": ["10", 0],
            "positive": ["2", 0],
            "negative": ["3", 0],
            "latent_image": ["5", 0]
        },
        "class_type": "KSampler",
        "_meta": {"title": "KSampler"}
    },
    "5": {
        "inputs": {"width": "{{width}}", "height": "{{height}}", "batch_size": 1},
        "class_type": "EmptyLatentImage",
        "_meta": {"title": "Empty Latent Image"}
    },
    "6": {
        "inputs": {"samples": ["4", 0], "vae": ["1", 2]},
        "class_type": "VAEDecode",
        "_meta": {"title": "VAE Decode"}
    },
    "8": {
        "inputs": {"images": ["6", 0]},
        "class_type": "PreviewImage",
        "_meta": {"title": "Preview Image"}
    },
    "9": {
        "inputs": {"preset": "PLUS (high strength)", "model": ["1", 0]},
        "class_type": "IPAdapterUnifiedLoader",
        "_meta": {"title": "IPAdapter Unified Loader"}
    },
    "10": {
        "inputs": {
            "weight": "{{ipadapter_weight}}",
            "start_at": "{{ipadapter_start_at}}",
            "end_at": "{{ipadapter_end_at}}",
            "weight_type": "prompt is more important",
            "model": ["9", 0],
            "ipadapter": ["9", 1],
            "image": ["14", 0]
        },
        "class_type": "IPAdapter",
        "_meta": {"title": "IPAdapter"}
    },
    "14": {
        "inputs": {"base64_image": "{{base64_image}}"},
        "class_type": "Base64ImageInput",
        "_meta": {"title": "Base64Image Input Node"}
    },
    "16": {
        "inputs": {"images": ["6", 0]},
        "class_type": "Base64ImageOutput",
        "_meta": {"title": "Base64Image Output Node"}
    }
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_generator_configurations', sa.Column('key', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_image_generator_configurations_key'), 'image_generator_configurations', ['key'], unique=True)
    # ### end Alembic commands ###
    
    # Data migration: создаем дефолтную конфигурацию
    connection = op.get_bind()
    
    result = connection.execute(
        sa.text("SELECT COUNT(*) FROM image_generator_configurations WHERE key = 'default'")
    ).scalar()
    
    if result == 0:
        config_json = json.dumps(DEFAULT_WORKFLOW_TEMPLATE, ensure_ascii=False)
        connection.execute(
            sa.text(
                "INSERT INTO image_generator_configurations (uuid, key, configuration) "
                "VALUES (:uuid, :key, :configuration)"
            ),
            {"uuid": str(uuid4()), "key": "default", "configuration": config_json}
        )
        print("✓ Default ComfyUI configuration created with key='default'")


def downgrade() -> None:
    # Data migration rollback: удаляем дефолтную конфигурацию
    connection = op.get_bind()
    connection.execute(
        sa.text("DELETE FROM image_generator_configurations WHERE key = 'default'")
    )
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_generator_configurations_key'), table_name='image_generator_configurations')
    op.drop_column('image_generator_configurations', 'key')
    # ### end Alembic commands ###
