"""

Revision ID: facfdc61a38b
Revises: 005
Create Date: 2025-11-05 17:39:19.854695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facfdc61a38b'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_events', sa.Column('story_uuid', sa.String(length=100), nullable=True))
    op.add_column('inbox_events', sa.Column('scene_number', sa.Integer(), nullable=True))
    op.drop_index('ix_inbox_events_processed_created', table_name='inbox_events')
    op.create_index(op.f('ix_inbox_events_scene_number'), 'inbox_events', ['scene_number'], unique=False)
    op.create_index(op.f('ix_inbox_events_story_uuid'), 'inbox_events', ['story_uuid'], unique=False)
    op.drop_index('ix_outbox_events_published_created', table_name='outbox_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_outbox_events_published_created', 'outbox_events', ['published', 'created_at'], unique=False)
    op.drop_index(op.f('ix_inbox_events_story_uuid'), table_name='inbox_events')
    op.drop_index(op.f('ix_inbox_events_scene_number'), table_name='inbox_events')
    op.create_index('ix_inbox_events_processed_created', 'inbox_events', ['processed', 'created_at'], unique=False)
    op.drop_column('inbox_events', 'scene_number')
    op.drop_column('inbox_events', 'story_uuid')
    # ### end Alembic commands ###
